version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./webfile/public:/var/www/html/
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    build: ./php/
    volumes:
      - ./webfile/public:/var/www/html/

  bdd:
    image: mysql:5.7
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: proj
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      SERVICE_TAGS: local
      SERVICE_NAME: mysql
  
  