version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./webfile/:/var/www/html/
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    build: ./php/
    volumes:
      - ./webfile/:/var/www/html/

